version: "3"
services:

  ############# External services

  
  memcached:
    image: memcached:1.4.38
    restart: unless-stopped
  

  
  mongodb:
    image: mongo:3.2.16
    # Use WiredTiger in all environments, just like at edx.org
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    restart: unless-stopped
    volumes:
      - ../../data/mongodb:/data/db
  

  
  mysql:
    image: mysql:5.6.36
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    volumes:
      - ../../data/mysql:/var/lib/mysql
    env_file: ../apps/mysql/auth.env
  
  mysql-client:
    image: mysql:5.6.36
    command: sh
    restart: "no"
    depends_on:
      - mysql

  
  elasticsearch:
    image: elasticsearch:1.5.2
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.name=openedx"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - ../../data/elasticsearch:/usr/share/elasticsearch/data
  

  openedx-assets:
    image: overhangio/openedx:3.6.0
    volumes:
      - ../../data/openedx:/var/www/openedx
    command: sh -c "rm -rf /var/www/openedx/staticfiles && cp -r /openedx/staticfiles/ /var/www/openedx/"

  nginx:
    image: nginx:1.13
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases: []
    volumes:
      - ../apps/nginx:/etc/nginx/conf.d/:ro
      - ../../data/openedx:/var/www/openedx:ro
      - ../../data/openedx-media:/var/www/openedx-media:ro
      
      
    depends_on:
      - lms
      - cms 

  
  rabbitmq:
    image: rabbitmq:3.6.10
    volumes:
      - ../../data/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
  

  
  smtp:
    image: namshi/smtp:latest
    restart: unless-stopped
  

  ############# Forum

  
  forum:
    image: overhangio/openedx-forum:3.6.0
    environment:
      SEARCH_SERVER: "http://elasticsearch:9200"
      MONGODB_AUTH: ""
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - mongodb
  

  ############# LMS and CMS

  
  lms:
    image: overhangio/openedx:3.6.0
    environment:
      SERVICE_VARIANT: lms
      SETTINGS: ${EDX_PLATFORM_SETTINGS:-tutor.production}
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/
      - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/
      - ../apps/openedx/config/:/openedx/config/
      - ../../data/lms:/openedx/data
      - ../../data/openedx-media:/openedx/media
    depends_on:
      - elasticsearch
      - forum
      - memcached
      - mongodb
      - mysql
      - rabbitmq
      - smtp
  

  
  cms:
    image: overhangio/openedx:3.6.0
    environment:
      SERVICE_VARIANT: cms
      SETTINGS: ${EDX_PLATFORM_SETTINGS:-tutor.production}
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/
      - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/
      - ../apps/openedx/config/:/openedx/config/
      - ../../data/cms:/openedx/data
      - ../../data/openedx-media:/openedx/media
    depends_on:
      - elasticsearch
      - memcached
      - mongodb
      - mysql
      - rabbitmq
      - smtp
  

  ############# LMS and CMS workers

  
  lms_worker:
    image: overhangio/openedx:3.6.0
    environment:
      SERVICE_VARIANT: lms
      SETTINGS: ${EDX_PLATFORM_SETTINGS:-tutor.production}
      C_FORCE_ROOT: "1" # run celery tasks as root #nofear
    command: ./manage.py lms celery worker --loglevel=info --hostname=edx.lms.core.default.%%h --maxtasksperchild 100
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/
      - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/
      - ../apps/openedx/config/:/openedx/config/
      - ../../data/lms:/openedx/data
      - ../../data/openedx-media:/openedx/media
    depends_on:
      - lms
  

  
  cms_worker:
    image: overhangio/openedx:3.6.0
    environment:
      SERVICE_VARIANT: cms
      SETTINGS: ${EDX_PLATFORM_SETTINGS:-tutor.production}
      C_FORCE_ROOT: "1" # run celery tasks as root #nofear
    command: ./manage.py cms celery worker --loglevel=info --hostname=edx.cms.core.default.%%h --maxtasksperchild 100
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/
      - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/
      - ../apps/openedx/config/:/openedx/config/
      - ../../data/cms:/openedx/data
      - ../../data/openedx-media:/openedx/media
    depends_on:
      - cms
  

  