---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/namespace.yml
- k8s/deployments.yml
- k8s/ingress.yml
- k8s/services.yml
- k8s/volumes.yml


# namespace to deploy all Resources to
namespace: openedx

# labels added to all Resources
# https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
commonLabels:
  app.kubernetes.io/instance: openedx-UgaKlOkBx5QEEzCZMv6Pyasc
  app.kubernetes.io/version: 3.6.0
  app.kubernetes.io/part-of: openedx
  app.kubernetes.io/managed-by: tutor
  

configMapGenerator:
- name: openedx-settings-lms
  files:
  - apps/openedx/settings/lms/development.py
  - apps/openedx/settings/lms/__init__.py
  - apps/openedx/settings/lms/production.py
  - apps/openedx/settings/lms/common.py
- name: openedx-settings-cms
  files:
  - apps/openedx/settings/cms/development.py
  - apps/openedx/settings/cms/__init__.py
  - apps/openedx/settings/cms/production.py
  - apps/openedx/settings/cms/common.py
- name: openedx-config
  files:
  - apps/openedx/config/cms.env.json
  - apps/openedx/config/lms.auth.json
  - apps/openedx/config/lms.env.json
  - apps/openedx/config/cms.auth.json
- name: nginx-config
  files:
  - apps/nginx/tutor.conf
  - apps/nginx/cms.conf
  - apps/nginx/extra.conf
  - apps/nginx/lms.conf
- name: mysql-config
  env: apps/mysql/auth.env


